#!/bin/bash

Results=/dcache/alice/jlomker/LHC23_PbPb_pass1
cp $Results/merge_runs.txt merge_runs.txt

while IFS= read -r line
do
  echo "deleting file.. ${line}"
  rm -rf "${Results}/${line}"
done < merge_runs.txt

rm -rf merge_runs.txt
