#!/bin/bash

Results=/dcache/alice/jlomker/LHC22_pass4_highIR_sampling
cp $Results/merge_runs.txt merge_runs.txt

while IFS= read -r line
do
  echo "deleting file.. ${line}"
  rm -rf "${Results}/${line}"
done < merge_runs.txt
