#!/bin/bash

Results=/dcache/alice/jlomker/LHC22_pass4_lowIR
cp $Results/merge_runs.txt merge_runs.txt

while IFS= read -r line
do
 # echo "deleting file.. ${line}"
  line="${line//'/AO2D.root'/}"
  #rm -rf "${Results}/${line}/CutVariations/"
done < merge_runs.txt

rm -rf merge_runs.txt
