#!/bin/bash

Results=/dcache/alice/jlomker/LHC22_pass4_highIR_sampling
cp $Results/merge_runs.txt merge_runs.txt

while IFS= read -r line
do
  line="${line//'/AO2D.root'/}"
  echo " '${line}' "
done < merge_runs.txt

rm -rf merge_runs.txt
